### ISSUE TITLE
Groovydoc task exception

### ISSUE THREAD

**Issue by apryamostanov** [virtualdogbert/enterprise-groovy-plugin#10]
Hi @virtualdogbert !

Yesterday I was trying to generate some Groovydocs, but found out that there is an exception happenning:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':groovydoc'.
> Script Failed: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  General error during class generation: java.lang.NoClassDefFoundError: groovy/lang/Script
  
  java.lang.RuntimeException: java.lang.NoClassDefFoundError: groovy/lang/Script
  	at org.codehaus.groovy.control.CompilationUnit.convertUncaughtExceptionToCompilationError(CompilationUnit.java:1129)
  	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1109)
  	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:649)
  	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:627)
  	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:604)
  	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:390)
  	at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
  	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:330)
  	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:327)
  	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
  	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:325)
  	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:309)
  	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:251)
  	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:261)
  	at groovy.lang.GroovyClassLoader$parseClass.call(Unknown Source)
  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
  	at groovy.util.ConfigSlurper.parse(ConfigSlurper.groovy:142)
  	at com.virtualdogbert.ast.EnterpriseGroovyASTTransformation.setupConfiguration(EnterpriseGroovyASTTransformation.groovy:183)
  	at com.virtualdogbert.ast.EnterpriseGroovyASTTransformation.visit(EnterpriseGroovyASTTransformation.groovy:64)
  	at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:320)
  	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:976)
  	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:651)
  	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:627)
  	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:604)
  	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:390)
  	at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
  	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:330)
  	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:327)
  	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
  	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:325)
  	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:543)
  	at groovy.lang.GroovyShell.parse(GroovyShell.java:555)
  	at groovy.lang.GroovyShell.parse(GroovyShell.java:591)
  	at org.codehaus.groovy.ant.Groovy.parseAndRunScript(Groovy.java:505)
  	at org.codehaus.groovy.ant.Groovy.execGroovy(Groovy.java:464)
  	at org.codehaus.groovy.ant.Groovy.execute(Groovy.java:322)
  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
  	at groovy.util.AntBuilder.performTask(AntBuilder.java:338)
  	at groovy.util.AntBuilder.nodeCompleted(AntBuilder.java:283)
  	at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:78)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
  	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
  	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
  	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:160)
  	at org.gradle.api.internal.project.antbuilder.AntBuilderDelegate.nodeCompleted(AntBuilderDelegate.java:118)
  	at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:154)
  	at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:67)
  	at org.gradle.api.internal.tasks.AntGroovydoc$2.doCall(AntGroovydoc.java:123)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
  	at groovy.lang.Closure.call(Closure.java:411)
  	at groovy.lang.Closure.call(Closure.java:427)
  	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:70)
  	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:52)
  	at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(DefaultIsolatedAntBuilder.java:152)
  	at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(DefaultIsolatedAntBuilder.java:134)
  	at org.gradle.api.internal.project.antbuilder.ClassPathToClassLoaderCache.withCachedClassLoader(ClassPathToClassLoaderCache.java:134)
  	at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder.execute(DefaultIsolatedAntBuilder.java:128)
  	at org.gradle.api.internal.tasks.AntGroovydoc.getGroovyVersion(AntGroovydoc.java:113)
  	at org.gradle.api.internal.tasks.AntGroovydoc.execute(AntGroovydoc.java:74)
  	at org.gradle.api.tasks.javadoc.Groovydoc.generate(Groovydoc.java:100)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
  	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
  	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
  	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
  	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:702)
  	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:669)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:401)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
  	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:390)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:373)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:79)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:210)
  	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
  	at java.util.Optional.orElseGet(Optional.java:267)
  	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
  	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
  	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
  	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
  	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
  	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
  	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
  	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
  	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
  	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
  	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
  	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
  	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
  	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:201)
  	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
  	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
  	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
  	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
  	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
  	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
  	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
  	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
  	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
  	at java.util.Optional.map(Optional.java:215)
  	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
  	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
  	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:77)
  	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
  	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
  	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
  	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
  	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
  	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:117)
  	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
  	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
  	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
  	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
  	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
  	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
  	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
  	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
  	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
  	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
  	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
  	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
  	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
  	at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.NoClassDefFoundError: groovy/lang/Script
  	at java.lang.ClassLoader.defineClass1(Native Method)
  	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  	at groovy.lang.GroovyClassLoader.access$500(GroovyClassLoader.java:89)
  	at groovy.lang.GroovyClassLoader$ClassCollector.createClass(GroovyClassLoader.java:592)
  	at groovy.lang.GroovyClassLoader$ClassCollector.onClassNode(GroovyClassLoader.java:609)
  	at groovy.lang.GroovyClassLoader$ClassCollector.call(GroovyClassLoader.java:613)
  	at org.codehaus.groovy.control.CompilationUnit$18.call(CompilationUnit.java:867)
  	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1095)
  	... 173 more
  Caused by: java.lang.ClassNotFoundException: groovy.lang.Script
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:762)
  	at groovy.lang.GroovyClassLoader$InnerLoader.loadClass(GroovyClassLoader.java:517)
  	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:872)
  	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:860)
  	... 182 more
```

The failing build:
https://github.com/INFINITE-TECHNOLOGY/SUPPLIES

**Comment by virtualdogbert** [comment]
Have you tried it without enterprise groovy installed? And if so does it work? I ask because ClassNotFoundException shouldn't be related to adding compile static especially since it' set to skip scripts...

**Comment by apryamostanov** [comment]
Good question.. Now I commented out the Groovy Enterprise Plugin, and Groovydoc task was OK.
After enabling it back - same exception.
It seems some sort of issue is there.

If that will help, tomorrow I can prepare a bare minimum build which simulates the problem.

That will help to cut out extra dependencies that are not having impact in this issue.

**Comment by virtualdogbert** [comment]
Crap, that doesn't make any sense, but I'll have to look at it to track down the issue. I wouldn't bother with a min build, I can just use your repo, it's not that big anyway. Although I won't have time to look at it this week/weekend, maybe next week... My August is pretty much booked time-wise...

**Comment by apryamostanov** [comment]
No issues! Thank you very much @virtualdogbert !
Sorry I forgot to mention - this is a medium-low priority issue. The Javadoc task works ok, and I am using that one temporary (with stub class saying that Groovydocs are temporary unavailable).

So any time next months is OK.

Let me know if any help will be required.

**Comment by virtualdogbert** [comment]
Finally got back to this, updated some error handling, so this should work using the new version:
1.0.3
Give it a try and tell me what happens.

**Comment by apryamostanov** [comment]
Thank you very much!
Please give me 2-3 days to test.

**Comment by virtualdogbert** [comment]
Well, it's been almost two weeks, guess you're busy.

**Comment by apryamostanov** [comment]
My avatar says it all:) Sorry for the delay. Tomorrow will retest and advise. 
Thank you!

**Comment by virtualdogbert** [comment]
No worries, just curious, and it's always good to get confirmation.

**Comment by apryamostanov** [comment]
hi @virtualdogbert 

Apologies for delay again.
Retested OK. Thank you very much!

I will incorporate this new version in my projects and therefore enhance my documents JAR distribution.
