### ISSUE TITLE
Exception suppression in conventions.groovy file search

### ISSUE THREAD

**Issue by apryamostanov** [virtualdogbert/enterprise-groovy-plugin#6]
Hi @virtualdogbert ,

I was trying to retest #5 (as per https://github.com/virtualdogbert/enterprise-groovy/pull/1) and faced below error which prevented config from being found during Gradle "Check" step:

```
java.lang.NullPointerException
	at com.virtualdogbert.ast.EnterpriseGroovyASTTransformation.getConfigFile(EnterpriseGroovyASTTransformation.groovy:175)
	at com.virtualdogbert.ast.EnterpriseGroovyASTTransformation.setupConfiguration(EnterpriseGroovyASTTransformation.groovy:198)
	at com.virtualdogbert.ast.EnterpriseGroovyASTTransformation.visit(EnterpriseGroovyASTTransformation.groovy:70)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:320)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:976)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:651)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:627)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:604)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:390)
	at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:330)
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:327)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:325)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:543)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:555)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:439)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:478)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:459)
	at groovy.test.GroovyAssert.assertScript(GroovyAssert.java:83)
	at groovy.util.GroovyTestCase.assertScript(GroovyTestCase.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at com.virtualgodbert.ast.egp.TemplateCompilationTest.test(TemplateCompilationTest.groovy:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

This exception is actually suppressed:
```
...
        } catch (Exception e) {
            return null //no config file defaults will be used
        }
```

May I suggest to slightly change this block to make exception handling more discrete? I.e. not suppress all exceptions.

**Comment by virtualdogbert** [comment]
This and #7 are the same issue so I'm closing this one.
